FROM node:14.9.0-alpine3.10
RUN npm install -g serve
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_BACKEND_URL https://esaude-backend-hml.azurewebsites.net
RUN npm run build
EXPOSE 3000
CMD ["serve", "-s", "-n", "build", "-l", "3000"]